#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'a test module'

__author__ = 'kanggege'

class person():
	def __init__(self,*args):
		self.name = args[0]
		self.__age = args[1] 
	
	def get_age():
		return self.__age
	
p = person('kanggege',21)
# print(p.__age) 报错，访问不到
p.__age = 10 # 实际上你又为该对象创建了一个 __age 属性，并不是类原来定义的属性
print(p.__age) # 10
print(p._person__age) # 21 不同的解释器可能会有不同的解析，既然不让你访问就别访问了吧